### ISSUE TITLE
Identical descriptions in corals

### ISSUE THREAD

**Issue by axcore** [mt-historical/decorations_sea#1]
The nodes `decorations_sea:coral_05` and `decorations_sea:coral_07` both contain the word "Red" in their description. This looks like a copy-paste error, because the matching schematics are called "red" and "crimson".

Fix: in `nodes.lua`, change line 111 to "Crimson" (it's the seventh item in the corals list).

**Comment by wsor4035** [comment]
feel free/please make a pull request in the future
